server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quanly?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect    # Đúng phiên bản MySQL 8
        show_sql: true
        format_sql: true
logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG
jwt:
  secret: MY_SECRET_KEY_1234567890_ABCDEFGHIJKLMNOPQRSTUVWXYZ
  expiration: 86400000  # 1 ngày (ms)
